version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5130:5130"
    environment:
      - ASPNETCORE_URLS=http://+:5130

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app 

  recommender-service:
    build:
      context: ./recommender_system
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - backend
